name: AVRO MED PUBLISH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ftp-server : ${{secrets.FTP_SERVER}}
          ftp-username : ${{secrets.FTP_USERNAME}}
          ftp-password : ${{secrets.FTP_PASSWORD}}
deployment:
  tasks:
    - export DEPLOYPATH=/home/avromedh/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
      # Add more steps for your build process
